on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login docker.pkg.github.com -u tubone24
